FAKE_DISCOVERY=[
'http://www.ibm.com',
'http://www.mbi.com',
'http://www.ksksk.com',
'http://www.ksaad.com',
'http://www.dadfd.com',
'http://www.xczc.com',
'http://www.awdncovi.com',
'http://www.kicmklnl.com'
]
